# Site settings
title: BLOG's for Flatiron School
header-img: img/home-bg.png
email: fkmccallion@gmail.com
copyright_name: fkmccallion
description: > # this means to ignore newlines until "baseurl:"
  Random Topics
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  fkmccallion
learn_profile: fkmccallion
email_username: fkmccallion@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
